Lab.Net.EF/Lab.Net.EF.MVC/Controllers/ProveedoresController.cs
using Lab.Net.EF.Logic.Empleado;
using Lab.Net.EF.Logic.Proveedor;
using Lab.Net.EF.MVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Net.EF.MVC.Controllers
{
    public class ProveedoresController : Controller
    {
        private ProveedorServicio _proveedorServicio = new ProveedorServicio();
        private ProveedorView _proveedorVista = new ProveedorView();

        public ActionResult Index(string cadenaBuscar = "")
        {
            var proveedorDtos = _proveedorServicio.GetAll(cadenaBuscar);
            var proveedorViews = proveedorDtos.Select(x => new ProveedorView()
            {
                Id = (int)x.Id,
                NombreCompania = x.NombreCompania,
                Ciudad = x.Ciudad,
            });

            return View(proveedorViews);
        }




        public ActionResult InsertarModificar(int? id)
        {
            if (id == null)
            {
                return View("InsertarModificar", new ProveedorView());
            }
            else
            {
                var proveedorObtenido = _proveedorServicio.ObtenerId(id.Value);
                _proveedorVista.Id = proveedorObtenido.SupplierID;
                _proveedorVista.NombreCompania = proveedorObtenido.CompanyName;
                _proveedorVista.Ciudad = proveedorObtenido.City;

                return View("InsertarModificar", _proveedorVista);

            }
        }


        [HttpPost]
        public ActionResult InsertarModificar(ProveedorView modelo)
        {
            if (ModelState.IsValid)
            {

                if (modelo.Id == 0)
                {

                    var proveedorNuevo = (new ProveedorDto
                    {
                        NombreCompania = modelo.NombreCompania,
                        Ciudad = modelo.Ciudad
                    });
                    _proveedorServicio.Insertar(proveedorNuevo);
                    return RedirectToAction("Index");
                }
                else
                {

                    var proveedorModificar = new ProveedorDto
                    {
                        Id = modelo.Id,
                        NombreCompania = modelo.NombreCompania,
                        Ciudad = modelo.Ciudad
                    };
                    _proveedorServicio.Modificar(proveedorModificar);
                    return RedirectToAction("Index");
                }

            }
            return View("InsertarModificar");
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                _proveedorServicio.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {

                return RedirectToAction("SinPermisos", "Error");
            }

        }
    }
}

Lab.Net.EF/Lab.Net.EF.MVC/Views/Proveedores/Index.cshtml
@model IEnumerable<Lab.Net.EF.MVC.Models.ProveedorView>
@{
    ViewBag.Title = "Proveedores Page";
}

<head>
    <link href="~/Views/Estilos/style.css" rel="stylesheet" />
</head>

<h1>Listado de Proveedores</h1>



<div class="container">
    <form method="get" action="@Url.Action("Index", "Proveedores")">
        <div class="row">
            <div class="col-md-6">
                <div class="input-group mb-3">
                    @Html.TextBox("cadenaBuscar", null, new { @class = "form-control", placeholder = "Buscar" })
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
                </div>
            </div>
        </div>
    </form>
    <div class="col-md-6 text-end">
        @Html.ActionLink("Insertar Proveedores", "InsertarModificar",
       "Proveedores", new { @class = "btn btn-outline-secondary" })
    </div>
</div>



<table class="table table-dark" style="margin-top:10px">
    <thead>

        <tr>

            <th scope="col">Nombre de la Compania</th>
            <th scope="col">Ciudad</th>
            <th scope="col">Eliminar</th>
            <th scope="col">Modificar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var proveedores in Model)
        {
            <tr>

                <th scope="row">@proveedores.NombreCompania</th>
                <td>@proveedores.Ciudad</td>
                <td>@Html.ActionLink("Eliminar", "Eliminar", new { id = proveedores.Id }, new { onclick = "return confirm('Esta seguro que desea Eliminar?')" })</td>
                <td>@Html.ActionLink("Modificar", "InsertarModificar", new { id = proveedores.Id })</td>
            </tr>
        }
    </tbody>
</table>

Lab.Net.EF/Lab.Net.EF.MVC/Views/Proveedores/InsertarModificar.cshtml
@model Lab.Net.EF.MVC.Models.ProveedorView
@{
    ViewBag.Title = "Insertar Proveedores";
}

@using (Html.BeginForm("InsertarModificar", "Proveedores", FormMethod.Post))
{
    @Html.HiddenFor(e => e.Id);

    <label>Nombre de la Compania:</label>
    @Html.TextBoxFor(e => e.NombreCompania)
    @Html.ValidationMessageFor(e => e.NombreCompania, "", new { @class = "text-danger" })
    <br />
    <label>Nombre de la Ciudad:</label>
    @Html.TextBoxFor(e => e.Ciudad)
    @Html.ValidationMessageFor(e => e.Ciudad, "", new { @class = "text-danger" })
    <br />
    <input type="submit" class="btn btn-success" value="Guardar" />


}